foreground #dddddd
background #1A1B26
background_opacity 0.80

# Don't prompt "Are you sure you want to close..." when quitting
confirm_os_window_close 0

# Nerd Font — required for Powerlevel10k glyphs (pkg: ttf-jetbrains-mono-nerd)
font_family      JetBrainsMono Nerd Font
font_size        13.0
