-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 8,
        col = {
            active_border = {
                colors = {"rgba(33ccffee)", "rgba(00ff99ee)"},
                angle = 20,
            },
        },
        gaps_in = 8,
        gaps_out = 10,
    },
})
