-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "26")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    cursor = {
        enable_hyprcursor = true,
        hide_on_key_press = true,
        no_warps = false,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            brightness = 1.02,
            contrast = 0.91,
            ignore_opacity = false,
            noise = 0.01,
            passes = 5,
            popups = true,
            size = 3,
            special = true,
            vibrancy = 0.11,
            xray = false,
        },
        dim_inactive = false,
        dim_strength = 0.2,
        fullscreen_opacity = 1.0,
        inactive_opacity = 1.0,
        rounding = 2,
        rounding_power = 2.0,
        shadow = {
            enabled = false,
            offset = "0 0",
            range = 20,
            render_power = 4,
        },
    },
    general = {
        border_size = 1,
        col = {
            active_border = "0xffb4befe",
        },
        extend_border_grab_area = 15,
        gaps_in = 5,
        gaps_out = 9,
        layout = "scrolling",
        resize_on_border = true,
        snap = {
            enabled = true,
            window_gap = 10,
        },
    },
    gestures = {
        workspace_swipe_forever = false,
    },
    input = {
        touchpad = {
            clickfinger_behavior = true,
            disable_while_typing = false,
            middle_button_emulation = true,
            natural_scroll = false,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        vrr = 0,
    },
})

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10.0,
    bezier = "default",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1600@165.00Hz",
    position = "-50x-1130",
    scale = 1.67,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + SPACE")
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("rofi -show drun"))
