-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Oxygen_Blue")
hl.env("XCURSOR_SIZE", "26")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
        hide_on_key_press = true,
        no_warps = false,
    },
    decoration = {
        blur = {
            passes = 4,
            popups = true,
            size = 6,
            special = true,
            xray = true,
        },
        dim_inactive = true,
        dim_strength = 0.2,
        inactive_opacity = 1.0,
        rounding = 10,
        rounding_power = 2.0,
        shadow = {
            enabled = true,
            offset = "0 0",
            range = 20,
            render_power = 4,
        },
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(c01c28ff)", "rgba(ed333bff)"},
                angle = 5,
            },
        },
        extend_border_grab_area = 15,
        gaps_in = 3,
        gaps_out = 8,
        layout = "dwindle",
        resize_on_border = true,
        snap = {
            enabled = true,
            window_gap = 10,
        },
    },
    gestures = {
        workspace_swipe_forever = false,
    },
    input = {
        touchpad = {
            disable_while_typing = false,
            middle_button_emulation = true,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        vrr = 1,
    },
})

-- Bezier curves
hl.curve("ease", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10.0,
    bezier = "default",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3.3,
    bezier = "ease",
    style = "slide",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.8,
    bezier = "easeOutQuint",
    style = "slide",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 30.0,
    bezier = "ease",
    style = "slide",
})
