ipc = on
preload = /home/bailey/Pictures/AGSpaper/walls-catppuccin-mocha/bluehour.jpg
wallpaper {
  monitor = eDP-1
  path = /home/bailey/Pictures/AGSpaper/walls-catppuccin-mocha/bluehour.jpg
  fit_mode = cover
}
splash = false