ipc = on

preload = /home/bailey/Pictures/Wallpaper/space/black-hole.png

wallpaper {
  monitor = DP-3
  path = /home/bailey/Pictures/Wallpaper/space/black-hole.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-1
  path = /home/bailey/Pictures/Wallpaper/space/black-hole.png
  fit_mode = cover
}
splash = false
