
general {
    before_sleep_cmd = true
    after_sleep_cmd = hyprctl dispatch dpms on
}



# 2 min → screen OFF (DPMS)
listener {
    timeout = 60
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}


