

ipc = on

preload = /home/bailey/Pictures/Wallpaper/spaceman/mountain-landscape-5120x2880-24317.jpg

wallpaper {
  monitor = eDP-1
  path = /home/bailey/Pictures/Wallpaper/spaceman/mountain-landscape-5120x2880-24317.jpg
  fit_mode = cover
}
splash = false
