# =============================
# HYPRLAND MAIN CONFIG
# =============================

source = ~/.config/hypr/host.conf
source = ~/.config/hypr/config/00-variables.conf
source = ~/.config/hypr/config/01-env.conf
source = ~/.config/hypr/config/monitors-$HOSTNAME.conf
source = ~/.config/hypr/config/03-input.conf
source = ~/.config/hypr/config/04-rules.conf
source = ~/.config/hypr/config/05-decoration.conf
source = ~/.config/hypr/config/06-animations.conf
source = ~/.config/hypr/config/07-misc.conf
source = ~/.config/hypr/config/08-keybinds.conf
source = ~/.config/hypr/config/09-autostart.conf
