-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        hide_on_key_press = true,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(3584e4ff)", "rgba(00ff99ee)"},
                angle = 45,
            },
        },
        layout = "dwindle",
        snap = {
            enabled = false,
        },
    },
})
