
general {
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}



# 30s idle → fully dim the screen (saves current brightness)
listener {
    timeout = 30
    on-timeout = brightnessctl -s set 1%   # fully dim level (use lower like 5 if you want darker)
    on-resume = brightnessctl -r           # move mouse/keyboard while dimmed → back to the brightness you had
}

# 60s (1 minute) idle → turn screen fully off
listener {
    timeout = 120
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}


