ipc = on

preload = /home/bailey/Pictures/Wallpaper/space/black-hole.png

wallpaper {
  monitor = eDP-1
  path = /home/bailey/Pictures/Wallpaper/space/black-hole.png
  fit_mode = cover
}
splash = false
