#############################
### ENVIRONMENT VARIABLES ###
#############################


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_DATA_DIRS,/home/bailey/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share


#these require sudo pacman ibus
env = GTK_IM_MODULE,ibus
env = QT_IM_MODULE,ibus
env = XMODIFIERS,@im=ibus
env = GDK_SCALE,2

#for hyprltm-net
env = PATH,$PATH:/home/bailey/.local/bin
