# =============================
# WINDOW RULES
# =============================

# ---- AGS LAYER RULES ----
layerrule = blur on, match:namespace launcher
layerrule = ignore_alpha 0.5, match:namespace launcher


# WINDOW RULES
#command = hyprctl clients
#sudo pacman -S hyprland-tools
windowrule {
  name = pavucontrol
  match:class = org.pulseaudio.pavucontrol

  float = true
  center = true
}

windowrule {
  name = steam-main
  match:class = steam

  float = true
  center = true
  size = 800 500
}

windowrule {
  name = Open Files
  match:class = chromium

  float = true
  center = true
  size = 700 400
}

windowrule {
  name = Bluetooth Devices
  match:class = blueman-manager

  float = true
  center = true
}

windowrule {
  name = Nautilus
  match:class = org.gnome.Nautilus

  float = true
  center = true
  size = 700 400
}


windowrule {
  name = btop
  match:title = btop

  float = true
  center = true
  size = 1000 650
}

#windowrulev2 = float,class:^(blueman-manager)$
#windowrulev2 = float,class:^(nm-connection-editor)$
#windowrulev2 = float,class:^(thunar)$
#windowrulev2 = float,class:^(steam)$

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = true
}

master {
    new_status = master
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = kitty-blur
    match:class = kitty
    opacity = 1
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}
