# =============================
# DECORATION
# =============================

decoration {
    rounding = 5
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 20
        render_power = 2
        color = rgba(00000055)
    }

    blur {
        enabled = true
        size = 4
        passes = 2
        vibrancy = 0.1696
        new_optimizations = true
    }
}
