# =============================
# AUTOSTART
# =============================
exec-once = cp ~/.config/hypr/hyprpaper-$HOSTNAME.conf ~/.config/hypr/hyprpaper.conf && hyprpaper
exec-once = ags run ~/.config/ags/app.ts
exec-once = nm-applet
exec-once = blueman-applet 
exec-once = $terminal 
exec-once = hypridle
exec-once = swaync


