[plugin_settings."tordex/system-updater"]
panel_placement = "floating"

[plugin_settings."yocraft/web-launcher"]
links = [
    "Noctalia wiki|https://docs.noctalia.dev",
    "Arch Wiki|https://wiki.archlinux.org"
]

[plugins]
enabled = [
    "jrohland/claudecode",
    "kenn/keybind-cheatsheet",
    "ashur-d/nvim-projects",
    "tmelik/system-monitor",
    "yocraft/web-launcher",
    "noctalia/wallhaven",
    "aabidk20/yt-music",
    "tordex/system-updater"
]
